# air.toml
[build]
bin = "bin/app" # Path to the output binary
cmd = "go build -o bin/app" # Build command
include_ext = ["go", "tpl", "tmpl", "html"] # File extensions to watch
exclude_dir = ["vendor", "bin", "scripts"] # Directories to exclude
exclude_file = ["air.toml"] # Files to exclude
follow_symlink = true # Follow symlinks
full_bin = "APP_ENV=dev bin/app" # Command to run the binary

[log]
level = "debug" # Log level
color = true # Enable color output
timestamp = true # Enable timestamp in logs

[watch]
delay = 200 # Delay in milliseconds before reloading
force_polling = false # Force polling for file changes
poll_interval = 1000 # Polling interval in milliseconds

[env]
file = ".env"